cmelab/flowerMD

hoomd_polymers/molecules.py, hoomd_polymers/tests/test_molecules.py
This PR makes the LJ chain class more flexible in terms of setting types, particle sequences, bond lengths and mass. The goal is to make it easier to run coarse-grained polymer simulations.  I've add a few unit tests for this class.
=> Make LJ chain class more flexible, add unit tests

hoomd_polymers/sim/simulation.py, hoomd_polymers/tests/test_simulations.py
This PR adds `hoomd.md.methods.DisplacementCapped` integrator to the simulation class. This integrator is based on NVE and puts a cap on the max displacement (length) per timestep. 
This integrator is mostly helpful when dealing with system with overlapping particles that commonly causes particle out of the box error.  Using this integrator in the beginning helps with relaxing the system and overcoming the overlaps.
=> Add DisplacementCapped Integrator to simulation

.github/workflows/pytest.yml, setup.py
The assets directory wasn't being included in `setup.py`, so when running `pip install .`  the user would not have those files.  I think this wasn't caught by tests because we used `pip install -e .` which creates symbolic links rather than copying over the package contents. I updated the `pytest.yml` file to use `pip install .`. I don't think it should cause any issues.
Solves #21
=> include assets dir in setup.py

hoomd_organics/base/system.py, hoomd_organics/library/simulations/tensile.py, hoomd_organics/tests/library/test_tensile.py, hoomd_organics/tests/modules/test_weld.py
While adding unit tests for the welding and tensile simulations I ran into a couple issues.
1. The box wasn't being set in a way that avoids overlapping particles along the boundaries. Now, the box lengths are longer in each direction by one lattice constant, and by a small amount (3 angstrom) in the z direction.
2. I fixed a couple issues with the tensile simulation class.
=> Fix for `Lattice` box and `Tensile` simulation. Add more unit tests

README.md
We had the old repo https and name in the README pytest badges.
=> update pytest codecov links, remove old code from README

environment-cpu.yml, environment-dev.yml, environment-gpu.yml
GMSO v0.11.1 with a couple bug fixes has been released now, so we don't need to install gmso from source via pip.
=> Update and simplify environment files

hoomd_organics/base/system.py, hoomd_organics/tests/base/test_system.py, hoomd_organics/tests/base_test.py, hoomd_organics/utils/__init__.py, hoomd_organics/utils/utils.py
This PR adds the scale charges functionality to the `System` class that was previously in a separate utils files, and includes some unit tests.
It works so that each negative charge is slightly increased and each positive charge is slightly decreased (all by the same amount) to achieve as close to a neutral charge as possible.
=> Fix scale charges, add unit tests

hoomd_organics/base/system.py, hoomd_organics/tests/base/test_system.py, hoomd_organics/tests/base_test.py, hoomd_organics/tests/utils/test_utils.py, hoomd_organics/utils/__init__.py, hoomd_organics/utils/utils.py
This PR moves a bunch of duplicated codes that validates reference units to the utils module. 
Unit tests have been added for all new functionalities.
=> Move reference values unit validation to utils

hoomd_organics/base/molecule.py, hoomd_organics/tests/base/test_system.py, hoomd_organics/tests/base_test.py
This PR fixes the gmso topology parameterization issue caused by name mismatch in mbuild compound.
For a Molecule loaded from a mol2 file, if we change the mbuild compound name, the name of its children does not change accordingly. When the forcefield dictionary with keys similar to the compound name is being applied to the system, the gmso topology is not parameterized because of this naming mismach. 
As a quick fix, this PR makes sure that the name is assigned to every child of the mbuild compound. However, more investigation needs to be done on gmso's behavior when converting an mbuild compound to a topology. (see the example in the comments).
=> Fix mismatched gmso residue name when molecule is loaded from mol2

hoomd_organics/base/simulation.py
This is a quick PR that adds a parameter to the run functions called `write_at_start` This is the same parameter that is in `hoomd.Simulation.run()`, we're just passing along the parameter. One difference is that we change the default value from `False` to `True`
=> add write_at_start parameters to run functions

hoomd_organics/base/simulation.py, hoomd_organics/tests/base/test_simulation.py
This PR sets up a separate logger for the GSD writer and logs energy, thermodynamic quantities and the pressure tensor to the GSD file.
=> Add GSD Logger and Pressure Tensor

hoomd_organics/base/system.py, hoomd_organics/tests/base/test_system.py
This PR makes it so that both `_create_hoomd_forcefield` and `_create_hoomd_snapshot` are only ever called once, and that the properties for both `hoomd_snapshot` and `hoomd_forcefield` can be used without having to re-run any gmso process.
We've gone back and forth and how to do this @marjanAlbouye so let me know if you think we're creating other issues by doing this...
=> Change behavior of hoomd object properties

environment-cpu.yml, environment-gpu.yml, hoomd_organics/base/simulation.py, hoomd_organics/library/simulations/tensile.py, hoomd_organics/tests/base/test_simulation.py, hoomd_organics/utils/__init__.py, hoomd_organics/utils/base_types.py
This PR upgrades the hoomd version to 4.1 and updates the `Simulation` class based on the changed on HOOMD 4.
The main changes are around setting up the integrator methods and thermostats.
Basically, in HOOMD v4 `NVT` and `NVE` methods are replaced with `hoomd.md.methods.ConstantVolume` and `NPT` method is replaced with `hoomd.md.methods.ConstantPressure`. 
In methods with constant a T, a thermostat needs to added from `hoomd.md.methods.thermostats".
Hoomd documentation for migrating to V4: https://hoomd-blue.readthedocs.io/en/v4.1.0/migrating.html#migrating-to-hoomd-v4
I still need to add some unit tests for thermostat setter.
=> Migrate to hoomd v4

hoomd_organics/base/system.py, hoomd_organics/tests/base/test_simulation.py, hoomd_organics/tests/base/test_system.py, hoomd_organics/tests/base_test.py, hoomd_organics/tests/library/test_tensile.py
This PR is related to #55 and a comment in there.  This opens up the `_apply_forcefield` and rather than it being called automatically inside of `System.__init__` is has to be called manually. The forcefield related parameters are moved out of `System.__init__` and into `apply_forcefield` and the PPPM arguments are added.
@marjanAlbouye and I have gone back and forth between thinking about how the `appy_forcefield` method should be handled, so let me know what you think and if you recognize any issues that might pop up from these changes.
=> Refactor apply_forcefield

hoomd_organics/base/__init__.py, hoomd_organics/base/forcefield.py, hoomd_organics/base/molecule.py, hoomd_organics/base/system.py, hoomd_organics/library/__init__.py, hoomd_organics/library/forcefields.py, hoomd_organics/tests/base/test_forcefield.py, hoomd_organics/tests/base/test_molecule.py, hoomd_organics/tests/base/test_system.py, hoomd_organics/tests/base_test.py, hoomd_organics/tests/library/test_forcefields.py, hoomd_organics/tests/library/test_tensile.py, hoomd_organics/tests/utils/test_ff_utils.py, hoomd_organics/utils/__init__.py, hoomd_organics/utils/base_types.py, hoomd_organics/utils/ff_utils.py
This PR applies  following changes to the  Molecule and System classes:
1) Move `force_field`  and `auto_scale` parameters from `System` init to `apply_forcefield` method.
Since applying forcefield is now done after system initialization, it makes sense to move all forcefield related parameters to `apply_forcefield`. 
The `apply_forcefield` method always sets the `reference_values` dictionary. When `auto_scale=True` the reference values will be set  based on the maximum parameter value and when its false, the values are set to 1 with default gmso units. As a result, we should always use `reference_values`  as the `base_units` parameter when calling gmso hoomd functions.
2) Added base classes for forcefield
Two new classes are added to the base module: `BaseXMLForcefield` and …
=> Update apply_forcefield and molecule forcefield

hoomd_organics/library/__init__.py, hoomd_organics/library/surfaces.py, hoomd_organics/tests/library/test_surfaces.py
This PR adds a recipe to create a graphene surface to the library. We can use this for creating a surface wetting workflow module.
=> Add graphene surface to library

jankflow/base/simulation.py
Fixes a bug where the box resizer isn't being removed from operations. This was causing issues when running NPT simulations after using `run_update_volume`
=> remove box resizer in run_update_volume

flowermd/base/system.py
I found a box where the translation of the 2nd chain in the unit cell of  `Lattice` was not being translated correctly. This should fix that
=> Fix translation in `Lattice`

paper/paper.md, setup.py
Still debugging `setup.py`. After recently installing the mol2 files in `assets/molecule_files` were not installed, this should fix that.
=> fix asset paths

CONTRIBUTING.md, README.md, paper/paper.bib, paper/paper.md
This PR takes care of the issues mentioned in the [pre-review](https://github.com/openjournals/joss-reviews/issues/5960#issuecomment-1770378283)
=> Address JOSS prereview comments

flowermd/base/system.py
In the `_scale_charges` method we set the site charge to zero if it's not defined, but we also need to give that 0 units of Coulombs which we weren't doing before.
=> Fix charge units when charge is 0

flowermd/base/molecule.py, flowermd/library/polymers.py, flowermd/tests/base/test_molecule.py, flowermd/tests/library/test_polymers.py
This PR removes `random_sequence` as a parameter when initializing a `CoPolymer`. Instead, `random_sequence` is set based on what is given for `sequence` when initializing a `CoPolymer`
=> Fix `PEKK`, remove `random_sequence` parameter from `CoPolymer`

environment-cpu.yml, environment-gpu.yml, setup.py
In preparation for making a conda-forge package for `flowermd` @marjanAlbouye and I updated the conda packages for both `grits` and `cmeutils`. This PR installs these packages from conda-forge rather than from source. I also pinned the latest version of hoomd and mosdef packages.
=> Update `environment.yml` to use conda-forge versions of `grits` and `cmeutils`

flowermd/base/molecule.py, flowermd/library/surfaces.py
Given some discussion with @marjanAlbouye about how to best design a surface wetting module, one of the first to-dos was making it so that the surfaces in `flowermd.library.surfaces` inherit from `flowermd.base.Molecule`.  This PR makes this change.
Here is an example of how we can create a graphene surface and apply a forcefield:
```
from flowermd.library import Graphene
from flowermd.library import OPLS_AA
from gmso.external import to_hoomd_snapshot, to_hoomd_forcefield
graphene = Graphene(
x_repeat=4,
y_repeat=4,
n_layers=2,
force_field=OPLS_AA()
)
graphene_snap = to_hoomd_snapshot(graphene.gmso_molecule)[0]
graph_ff = to_hoomd_forcefield(graphene.gmso_molecule, r_cut=2.5)[0]
```
This was the first step needed in order for the design choices we discussed in a class that combines a …
=> `Graphene` now inherits from `Molecule`

flowermd/__version__.py, setup.py
The surface wetting module wasn't installing, so this fixes `setup.py` to install all sub dirs in `flowermd/modules/`.
=> fix setup.py to install all modules

flowermd/modules/welding/__init__.py
This is a quick PR that adds the `utils.py` file located in the welding module to `__init__.py` so that its funcitons can be imported.
=> Fix import for `add_void_particles` in `modules.welding.utils`

flowermd/base/simulation.py, flowermd/tests/base/test_simulation.py, flowermd/tests/base/test_system.py, flowermd/tests/utils/test_utils.py
This PR adds and error that is thrown if the  `forcefield` parameter of `Simulation` is not a sequence of `hoomd.md.force.Force` objects.
=> Add type check for forcefield parameter in `Simulation`

environment-dev.yml, environment.yml, flowermd/modules/welding/welding.py
This is a quick bug fix that changes `interface_axis` to a numpy array as the behavior of `np.where` was not working as expected on certain data types (e.g. tuples).
=> Bug fix in `Interface` to duplicate and shift along the correct axis

flowermd/base/molecule.py, flowermd/base/system.py, flowermd/tests/base/test_system.py, flowermd/tests/library/test_polymers.py
This fixes #128 by adding a try/except statement to `Molecule._align_backbones_z_axis` in the case that the particles don't have elements.
=> Fix `Lattice` system class for coarse-grained molecules

.github/workflows/pytest.yml
`macos-latest` switched to using ARM-based MacOS, so if we want to test on intel MacOS we have to use macos-13. This PR makes it so we now use both.
=> Update MacOS images used in os-matrix in CI workflow

.github/workflows/pytest.yml, flowermd/base/molecule.py, flowermd/base/system.py, flowermd/tests/base/test_molecule.py, flowermd/tests/base/test_system.py
The polymer builder in mBuild now lets you form periodic bonds, which basically just means you can bond the head and tail ports together. This should be useful for simulating polymer lattices where we want bonds formed across the the chain length direction.
This PR adds an option to the `Polymer` class that lets you use this built in feature in mBuild
=> Add support for mBuild's periodic polymer bonding

.github/workflows/pytest.yml, flowermd/base/simulation.py, flowermd/tests/base/test_simulation.py
This PR adds `Simulation.save_simulation_pickle` and `Simulation.from_simulation_pickle` methods that save everything needed to save and restart a simulation (state, forces, reference values, and kwargs).
A couple notes:
1. The `save_simulation_pickle` method writes a binary string to the file that is checked by `from_simulation_pickle` before opening the pickle with `pickle.load`.
2. Using local snapshots, or `state.get_snapshot()` aren't pickleable, so we have to save a `temp.gsd.` file, then pickle the `gsd.hoomd.Frame` state instead.
=> Add data structure to save and restart a simulation.
